#ifndef _SUPERNOVAKERNEL_VERSION_DEFINITONS_
#define _SUPERNOVAKERNEL_VERSION_DEFINITONS_

#define VERSION_MAJOR	   0
#define VERSION_MINOR	   0
#define VERSION_RELEASE	   0
#define VERSION_BUILD	 344

#define COMPILE_DATE_YEAR	 114
#define COMPILE_DATE_MONTH	  10
#define COMPILE_DATE_DAY	  17
#define COMPILE_DATE_STRING	__DATE__

#define COMPILE_TIME_HOUR	   6
#define COMPILE_TIME_MINUTE	  49
#define COMPILE_TIME_SECOND	   7
#define COMPILE_TIME_STRING	__TIME__

#endif
